'use client';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Headphones,MessageCircle,Sparkles,Send,CheckCircle2,Paperclip,RefreshCw,ShieldCheck,Clock,Code2} from 'lucide-react';
import {toast} from 'sonner';
import {Checkbox} from '@/components/ui/checkbox';
import {askGroq} from '@/lib/groq-browser';
import {newId} from '@/lib/id';
import VoiceCallPanel from '@/components/voice-call';
type Any=any;
async function api(path:string,body?:Any){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data:Any=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível concluir.');return data;}
const when=(t:string)=>new Date(t).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
export function ChatTranscript({messages}:Any){return <div className="chat-messages" role="log" aria-live="polite" aria-label="Histórico da conversa">{messages.map((m:Any)=><article key={m.id} className={'chat-message '+m.role}><div className="message-author">{m.role==='assistant'?<Sparkles size={15}/>:m.role==='support'?<Headphones size={15}/>:null}<b>{m.role==='user'?'Cliente':m.role==='support'?'Equipe de suporte':m.role==='system'?'Atendimento':'Assistente ResolveTech'}</b><time>{when(m.created)}</time></div><p>{m.content}</p>{m.source.startsWith('groq:')&&<small>IA · GPT-OSS 120B</small>}</article>)}</div>}
export default function ChatWorkspace({demand:initial,user,back,onChange}:Any){
 const [d,setD]=useState(initial),[draft,setDraft]=useState(''),[consent,setConsent]=useState(!!initial.chat.ai_consent),[sending,setSending]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Any>(null);const end=useRef<HTMLDivElement>(null);const alive=useRef(true);
 const chat=d.chat, client=user.role==='CLIENT',isHuman=chat.phase==='SUPPORT',closed=chat.phase==='RESOLVED',aiReady=d.integrations.groqConfigured;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 async function apply(next:Any){if(!alive.current)return;setD(next);await onChange?.(next);}
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[chat.messages.length]);
 useEffect(()=>{if(!isHuman)return;let cancelled=false;const timer=setInterval(()=>api('demands/'+d.id).then(next=>{if(!cancelled)setD(next)}).catch(()=>{}),5000);return()=>{cancelled=true;clearInterval(timer)}},[isHuman,d.id]);
 const unanswered=chat.messages.filter((m:Any)=>m.role==='user'&&m.source==='app'&&!chat.messages.some((a:Any)=>a.reply_to===m.id)).at(-1);
 async function send(retry?:Any){
  const content=retry?.content||draft.trim();if(!content||sending)return;
  const payload=retry||pending||{messageId:newId(),content};setSending(true);setError('');setPending(payload);
  try{const aiResult=isHuman?undefined:await askGroq(chat.messages,payload.content,chat.category,chat.guidance);const next=await api('chat/'+d.id+'/'+(isHuman?'reply':'message'),{...payload,consent,aiResult});await apply(next);setPending(null);if(draft.trim()===payload.content)setDraft('');}
  catch(e:Any){setError(e.message);try{const next=await api('demands/'+d.id);if(alive.current)setD(next)}catch{};}
  finally{if(alive.current)setSending(false);}
 }
 async function handoff(){setWorking(true);setError('');try{await apply(await api('chat/'+d.id+'/handoff',{}));setPending(null);toast.success('Solicitação registrada. Aguarde o suporte atender você por este chat.');}catch(e:Any){setError(e.message)}finally{setWorking(false)}}
 async function satisfied(){setWorking(true);try{await apply(await api('chat/'+d.id+'/feedback',{satisfied:true}));toast.success('Atendimento concluído.');}catch(e:Any){setError(e.message)}finally{setWorking(false)}}
 async function upload(file:File){setWorking(true);try{if(file.size>10*1024*1024)throw new Error('Limite de 10 MB por arquivo.');const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});await apply(await api('demands/'+d.id+'/upload',{name:file.name,data}));toast.success('Anexo salvo para a equipe. A IA não lê o conteúdo dos anexos.');}catch(e:Any){setError(e.message)}finally{setWorking(false)}}
 return <><button className="back-link" onClick={back}><ArrowLeft size={16}/>Voltar</button><div className="page-heading"><div><p className="eyebrow">{d.public_id} · {d.company_name}</p><h1>{closed?'Atendimento concluído':isHuman?'Atendimento assistido':'Vamos resolver juntos'}</h1><p>{chat.category}</p></div><div className="support-top"><span className={'chat-phase '+(closed?'done':'')}>{closed?<CheckCircle2 size={16}/>:isHuman?<Headphones size={16}/>:<Sparkles size={16}/ >}{closed?'Concluído':isHuman?'Com o suporte':'Investigação com IA'}</span>{client&&!closed&&<div className="support-top-actions"><b>Falar com o suporte</b><button className="btn secondary" disabled={working} onClick={isHuman?()=>document.querySelector<HTMLTextAreaElement>('.chat-compose textarea')?.focus():handoff}><MessageCircle size={17}/>Por chat</button><VoiceCallPanel demandId={d.id} compact onBeforeJoin={isHuman?undefined:handoff}/></div>}</div></div><div className="conversation-layout"><section className="panel chat-panel"><header className="chat-panel-header"><span className="chat-agent-icon">{isHuman?<Headphones/>:<Sparkles/>}</span><div><h2>{isHuman?'Equipe de suporte':'Assistente ResolveTech'}</h2><p>{isHuman?'Seu histórico acompanha o atendimento.':'Uma conversa para entender o problema e tentar resolver.'}</p></div></header>
 {!aiReady&&!isHuman&&!closed&&<div className="chat-notice">A conexão com a IA aguarda configuração da empresa. Você pode solicitar suporte agora.</div>}
 <ChatTranscript messages={chat.messages}/>{sending&&<div className="thinking" role="status"><Sparkles size={16}/>{isHuman?'Enviando mensagem…':'Investigando o contexto da sua conversa…'}</div>}<div ref={end}/>
 {!closed&&client&&chat.phase==='AWAITING_FEEDBACK'&&chat.messages.some((m:Any)=>m.source.startsWith('groq:'))&&<div className="feedback-card"><h3>{chat.phase==='AWAITING_FEEDBACK'?'Isso ajudou a resolver seu problema?':'Já conseguiu resolver?'}</h3><p>Você pode continuar conversando, concluir ou pedir ajuda à equipe.</p><div className="row wrap"><button className="btn" disabled={working||sending} onClick={satisfied}><CheckCircle2 size={17}/>Sim, estou satisfeito</button><button className="btn secondary" disabled={working} onClick={handoff}>Não, quero suporte<ArrowRight size={17}/></button></div></div>}
 {error&&<div role="alert" className="chat-error">{error}{pending&&<button disabled={sending} onClick={()=>send(pending)}>Tentar novamente</button>}</div>}
 {!closed&&<div className="chat-compose">{!isHuman&&!chat.ai_consent&&<label className="tick"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>Autorizo enviar esta conversa à Groq para investigar meu problema.</span></label>}{unanswered&&!sending&&!isHuman&&<div className="chat-notice">Sua última mensagem foi salva e ainda não tem resposta. <button onClick={()=>send({messageId:unanswered.id,content:unanswered.content})}>Tentar responder novamente</button></div>}<form onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="Sua mensagem" value={draft} maxLength={6000} onChange={e=>{setDraft(e.target.value);if(!unanswered)setPending(null)}} placeholder={isHuman?'Envie uma mensagem para a equipe…':'Conte o que aconteceu, com suas palavras…'} rows={3} disabled={sending} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(draft.trim()&&(isHuman||consent&&aiReady)&&!unanswered)send()}}}/><div className="composer-actions"><label className="attach-chat" title="Anexar arquivo para o suporte"><Paperclip size={19}/><span>Anexar</span><input type="file" accept=".png,.jpg,.jpeg,.pdf,.txt,.csv,.zip" disabled={working} onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value=''}}/></label><small>Enter envia · Shift + Enter quebra linha</small><button className="btn" type="submit" disabled={sending||!draft.trim()||!isHuman&&(!consent||!aiReady||!!unanswered)}><Send size={17}/>{sending?'Enviando…':'Enviar'}</button></div></form></div>}
 {closed&&<div className="chat-closed"><CheckCircle2/><b>Conversa encerrada</b><p>O histórico continua salvo nas suas demandas.</p></div>}</section><aside className="stack chat-aside"><section className="panel pad"><h2>Sobre a conversa</h2><div className="chat-meta"><span>Empresa</span><b>{d.company_name}</b><span>Problema inicial</span><b>{chat.category}</b><span>Protocolo</span><b>{d.public_id}</b></div><p className="small muted">As orientações da IA são sugestões. Não envie senhas, tokens ou informações sensíveis.</p></section>{d.attachments.length>0&&<section className="panel pad"><h2>Anexos da demanda</h2>{d.attachments.map((f:Any)=><a key={f.id} className="attachment" href={'/api/files/'+f.id}><Paperclip size={16}/>{f.name}</a>)}<p className="small muted">Disponíveis para a equipe; não são analisados pelo modelo.</p></section>}</aside></div></>
}
export function StaffConversation({demand,user,refresh}:Any){
 const [body,setBody]=useState(''),[busy,setBusy]=useState(false);const chat=demand.chat;const staff=['ADMIN','SUPPORT'].includes(user.role);
 useEffect(()=>{const t=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(t)},[demand.id]);
 async function reply(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('chat/'+demand.id+'/reply',{messageId:newId(),content:body});setBody('');await refresh()}catch(e:Any){toast.error(e.message)}finally{setBusy(false)}}
 async function upload(file:File){setBusy(true);try{if(file.size>10*1024*1024)throw new Error('O limite por arquivo é 10 MB.');const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});await api('demands/'+demand.id+'/upload',{name:file.name,data});await refresh();toast.success('Arquivo anexado à demanda e disponível para o desenvolvimento.')}catch(e:Any){toast.error(e.message)}finally{setBusy(false)}}
 async function close(){if(!window.confirm('Encerrar este atendimento? O cliente não poderá enviar novas mensagens nesta conversa.'))return;setBusy(true);try{await api('chat/'+demand.id+'/close',{});await refresh();toast.success('Atendimento encerrado.')}catch(e:Any){toast.error(e.message)}finally{setBusy(false)}}
 return <section className="panel pad"><div className="staff-conversation-heading"><div><h2>Conversa investigativa e atendimento</h2><p className="muted">Este chat reúne toda a comunicação entre cliente e suporte.</p></div></div><ChatTranscript messages={chat.messages}/>{staff&&chat.phase==='SUPPORT'&&<form onSubmit={reply}><textarea aria-label="Responder ao cliente" value={body} onChange={e=>setBody(e.target.value)} rows={3} placeholder="Responda ao cliente pelo chat…"/><div className="row wrap"><button className="btn" disabled={busy||!body.trim()}><Send size={17}/>Responder ao cliente</button><label className="btn secondary attach-chat"><Paperclip size={17}/>Anexar imagem ou arquivo<input type="file" accept=".png,.jpg,.jpeg,.pdf,.txt,.csv,.zip" disabled={busy} onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value=''}}/></label><button type="button" className="btn secondary" disabled={busy} onClick={close}><CheckCircle2 size={17}/>Resolvido: finalizar</button></div></form>}{demand.attachments?.length>0&&<div><h3>Arquivos da conversa</h3>{demand.attachments.map((f:Any)=><a key={f.id} className="attachment" href={'/api/files/'+f.id}><Paperclip size={16}/>{f.name}</a>)}</div>}{chat.phase==='RESOLVED'&&<div className="chat-closed"><CheckCircle2/><b>Atendimento finalizado</b></div>}</section>}
